$schema: https://raw.githubusercontent.com/streetsidesoftware/cspell/main/cspell.schema.json
version: "0.2"
ignorePaths:
  - node_modules
  - bun.lockb
  - .tsbuildinfo
  - .gitignore
  - .github
  - .next
  - drizzle
  - "**/*.svg"
  - .vscode/extensions.json
  - public
  - tsconfig.tsbuildinfo
words:
  - Abebe
  - callees
  - classname
  - clsx
  - commitlint
  - Dismissable
  - Elipssis
  - ianvs
  - imeline
  - Instructise
  - journaling
  - lockb
  - Naol
  - nums
  - oslojs
  - Serverside
  - shadcn
  - superjson
  - tanstack
  - Tesema
  - Teshome
  - trpc
  - tseslint
  - turbopack
  - typecheck
